AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    oha-geruge backend sam.

Parameters:
  CallbackUri:
    Type: String
  ConsumerKey:
    Type: String
  ConsumerSecret:
    Type: String

Globals:
  Function:
    Timeout: 30
    Environment:
      Variables:
        CALLBACK_URI: !Ref CallbackUri
        CONSUMER_KEY: !Ref ConsumerKey
        CONSUMER_SECRET: !Ref ConsumerSecret

  Api:
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'Content-Type'"
      AllowOrigin: "'*'"

Resources:
  RequestTokenFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: twitter-auth/
      Handler: app.requestToken
      Runtime: nodejs8.10
      Events:
        RequestToken:
          Type: Api
          Properties:
            Path: /request_token
            Method: post

  AccessTokenFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: twitter-auth/
      Handler: app.accessToken
      Runtime: nodejs8.10
      Events:
        AccessToken:
          Type: Api
          Properties:
            Path: /access_token
            Method: post

  GetUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: twitter-auth/
      Handler: app.getUser
      Runtime: nodejs8.10
      Events:
        AccessToken:
          Type: Api
          Properties:
            Path: /get_user
            Method: get

  TweetFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: twitter-auth/
      Handler: app.tweet
      Runtime: nodejs8.10
      Policies:
        - S3ReadPolicy:
            BucketName: oha-geruge-images
      Events:
        AccessToken:
          Type: Api
          Properties:
            Path: /tweet
            Method: post
